services:
  gateway:
    build: ./gateway
    ports:
      - "9000:9000"
    container_name: gateway-service

  crawlerservice:
    build: ./services/crawlerservice
    ports:
      - "9001:9001"
    container_name: crawlerservice

  poirecommendservice:
    build: ./services/poirecommendservice
    container_name: poirecommendservice
    ports:
      - "8003:8003"
    volumes:
      - ./services/poirecommendservice/app:/app/app
    restart: unless-stopped
